### ISSUE TITLE
CallAdmin Desktop Client Error when shutting down

### ISSUE THREAD

**Issue by AzaZPPL** [popoklopsi/CallAdmin-Client#1]
The CallAdmin Desktop Client shows an error when shutting down. This happens everytime I shutdown my pc while the client is running. I have to press ok to the error and afterwards the pc finally shuts down.

**Comment by Impact123** [comment]
Can you tell us more about that error you're seeing?

**Comment by AzaZPPL** [comment]
This is the error: http://prntscr.com/6s20eu

I'm on Windows 8.1 Pro x64

**Comment by ghost** [comment]
Sorry for the late replay. Currently I'm in an update phase for the client. 
The new version will have a much better structure and i hope this will be fixed then.
