### ISSUE TITLE
Little sourcebans support ( sb_admins.cfg instead of calladmin_steam_steamidlist.cfg)

### ISSUE THREAD

**Issue by SHAREN** [popoklopsi/CallAdmin-Client#3]
Because then when you add the administrator to SourceBans have to re-add to calladmin_steam_steamidlist
or simply forget to add or remove

file location /addons/sourcemod/configs/sourcebans/sb_admins.cfg
sb_admins.cfg example

```
"Admins"
{
    "nickname"
    {
        "auth"      "steam"
        "identity"      "STEAM_1:1:53533556"
        "group"     "Admins"
    }
    "nickname2"
    {
        "auth"      "steam"
        "identity"      "STEAM_1:0:443849190"
        "group"     "Admins"
    }
    "nickname3"
    {
        "auth"      "steam"
        "identity"      "STEAM_1:1:53479065"
        "group"     "Admins"
    }
}
```

I think that most servers use SourceBans

**Comment by ghost** [comment]
This is the wrong repository for this. 
Please ask your request here: https://github.com/Impact123/CallAdmin

Thank you!
