### ISSUE TITLE
Desktop Client Crashing

### ISSUE THREAD

**Issue by JamsRepos** [popoklopsi/CallAdmin-Client#6]
Hey,

It seems whenever I open the desktop client, around 10 seconds or so it says the application is no longer responding and closes. It seems to be when it checks for a new claim but I am unsure as of what may be causing it. I've looked into backwards compatibility etc and no change at all.

![Image](http://i.imgur.com/L8D9xto.png)

Are you aware of this?

**Comment by ghost** [comment]
Mh weird, did not here about it, yet. But The client is already in a big development process (for the next CallAdmin version), but i only have time for it again in September, because now is exam time and then holidays :)

**Comment by JamsRepos** [comment]
Thanks for the reply, further diagnosis it seems to happen when I put my url as https://thenexusnation.com/calladmin/

When I have no url it is fine and does not crash. Seems to happen when it checks for a new call.

**Comment by dordnung** [comment]
Could you try it without https? It's just an assumption

**Comment by ghost** [comment]
Could you try it without https? It's just an assumption
