### ISSUE TITLE
Desktop Client Crashes

### ISSUE THREAD

**Issue by CosmicHikari** [popoklopsi/CallAdmin-Client#7]
I'm aware someone else has posted, but now this isnt just one person, all 40 of my staff are having the same issue.

-> Connected to Steam
-> Checking for Update..
-- crashes--

thats all there is to it. Idk what else to say, I've run administrator, I've checked the URL and all is fine, just today it's dead.

**Comment by CosmicHikari** [comment]
![image](https://user-images.githubusercontent.com/16886014/32972119-8ea2a646-cbbe-11e7-9c56-0ef5025b3b0f.png)

**Comment by dordnung** [comment]
Hey,

thanks for your message.
The problem is because I've updated my update site to only use SSL and the client has problems with it.
I've disabled that for now, so it should work again.
